# Usage: Create the symlink '~/.bashrc' and point it to this file
# Author: Mattias Arrelid (with lots of inspiration from Rasmus Andersson)

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# EXPORTS

  # Don't put duplicate lines in the history
  export HISTCONTROL=ignoreboth:erasedups

  # We want our applications to use American English as far as possible,
  # since most translations suck anyway...
  export LC_CTYPE=en_US.UTF-8
  export LANG=en_US.UTF-8

  # Add paths to our $PATH
  export PATH=/usr/local/bin:/usr/local/sbin:/usr/sbin:$PATH

  # Python customizations
  if [ -x ~/.pythonrc.py ]; then
    export PYTHONSTARTUP=~/.pythonrc.py
  fi

  # Use nano as editor
  export EDITOR="vim"
  export VISUAL_EDITOR=$EDITOR
  export SVN_EDITOR=$EDITOR

  # Enforce pretty colors when listing stuff
  # Guide: http://twistedcode.blogspot.com/2008/04/lscolors-explained.html
  # See "dircolors -p" for more examples
  export CLICOLOR=1
  export LSCOLORS=AxbxcxdxCxegedabagacad


# SHELL OPTIONS

  shopt -s cmdhist       # Make bash try to store multiline commands in one history entry
  shopt -s cdspell       # Correct minor spelling errors in a cd command
  shopt -s histappend    # Append to history rather than overwrite
  shopt -s checkwinsize  # Update lines and columns after each command (if necessary)
  shopt -s dotglob       # Includes filenames beginning with a '.' in the results of filename expansion.


# ALIASES

  alias l='ls -hlAF'            # Fancy listing of files and directories


# PROMPT

  # Updates the prompt with colors, title etc. Kudos to Rasmus Andersson for doing the dirty work!
  alias _userpwd='/usr/bin/perl -e '"'"'use Cwd;my $d=cwd();my $h=$ENV{"HOME"};my $dl=length($d);my $hl=length($h);if(($dl>=$hl)&&($h==substr($d,$hl))){print "~".substr($d,$hl,$dl);}else{print $d;}'"'"
  _PS1prefix="\[\e[40;32;1m\]>>> "
  _PS1user="\[\e[31;1m\]\u"
  _PS1meta1="\[\e[0;40m\]@\h\[\e[0;40m\]:\[\e[33;1m\]\w \[\e[0;1;30m\] \t \[\e[36;1m\]"
  _PS1end="\n\[\e[36;1m\]\\$\[\e[0m\] "
  export PROMPT_COMMAND='PS1="$_PS1prefix$_PS1user$_PS1meta1$_PS1end"; echo -ne "\033]0;`id -un`@`hostname -s`:`_userpwd` [$(date +%H:%M)]\007"'


# MISC

  # Enable bash completion if possible
  if [ -f `brew --prefix`/etc/bash_completion ]; then
    . `brew --prefix`/etc/bash_completion
  fi
