" Generic settings
set encoding=utf-8         " utf-8 is the shiznitz
set guioptions=cem         " use the console for confirmation dialogues + display the tab bar in the gui + show the menu bar
set laststatus=2           " always show the status bar
set nobackup               " use _other_ means as backup than *.orig files
set nocompatible           " don't care about vi
set noswapfile             " swap files - good if you're editing large files on a daily basis maybe, but i'm not...
set number                 " everyone loves row numbers
set ruler                  " show information about current row/col
set showcmd                " show useful information about the current state of keyboard input in normal mode
set showtabline=2          " always show the tab bar

" Change the statusline to show some more stuff than just the defaults
set statusline=%f\ \                             " Relative file name
set statusline+=%n\ \                            " Buffer number
set statusline+=%m                               " Modified flag
set statusline+=%y                               " File type
set statusline+=%{fugitive#statusline()}\        " Current git branch (if any)
set statusline+=%=                               " Left/right separator
set statusline+=%c,\                             " Cursor column
set statusline+=%l/%L                            " Cursor line/total lines
set statusline+=\ %P                             " Percent through file

let mapleader=","   " the leader key should be easy to type (',' is easier than '\')
syntax on           " enable syntax highlighting depending on file type

" Whitespacing and line/row breaks
set tabstop=2                                       " a tab is two spaces...
set softtabstop=2                                   " ...and the corresponding backspace removes the same amount of space
set shiftwidth=2                                    " indentation should follow tabstop, or stuff will have different indentation
set expandtab                                       " expand tabs into spaces
set nowrap                                          " seriously, don't wrap by default
set linebreak                                       " break on word barriers
set listchars=tab:»·,trail:·,precedes:<,extends:>   " highlight these little bastard when 'set list' is invoked
set backspace=indent,eol,start                      " backspace through everything in insert mode

" Searching
set hlsearch    " highlight matches
set incsearch   " incremental searching
set ignorecase  " searches are case insensitive...
set smartcase   " ... unless they contain at least one capital letter

" Tab completion behavior when opening files
set wildmode=list:longest,list:full  " complete as much as possible, then full for each press on tab

" Turn off hithe last search
map <silent> <C-L> :set hlsearch! hlsearch?<CR>

" When moving around using j/k, jump _within_ wrapped lines too (since you probably don't want to skip an entire paragraph).
nnoremap j gj
nnoremap k gk

" Allow saving of files as sudo when you forget to start vim using sudo.
cmap w!! %!sudo tee > /dev/null %

" Setup vundle
filetype off                                  " Required
set rtp+=~/.vim/bundle/vundle/                " Make sure to clone vundle.git here first
call vundle#rc()

Bundle 'gmarik/vundle'
Bundle 'tpope/vim-fugitive'
Bundle 'Lokaltog/vim-easymotion'
Bundle 'git://git.wincent.com/command-t.git'
Bundle 'altercation/vim-colors-solarized'
Bundle 'bitc/vim-bad-whitespace'
Bundle 'tpope/vim-unimpaired'

" Vundle setup complete, reset filetype
filetype plugin indent on

if has("autocmd")
  autocmd FileType python setlocal ts=4 sts=4 sw=4 expandtab
  autocmd FileType c,cpp,objc setlocal ts=2 sts=2 sw=2 expandtab
  autocmd FileType text setlocal ts=2 sts=2 sw=2 expandtab wrap
endif

" Command-T configuration
let g:CommandTMaxHeight=15

" Use the solarized color scheme
set background=dark
let g:solarized_termcolors=256  " Fancy fallback so that you don't have to change your terminal's color scheme
colorscheme solarized
