" Generic settings
set encoding=utf-8         " utf-8 is the shiznitz
set guioptions=cem         " use the console for confirmation dialogues + display the tab bar in the gui + show the menu bar
set laststatus=2           " always show the status bar
set nobackup               " use _other_ means as backup than *.orig files
set nocompatible           " don't care about vi
set noswapfile             " swap files - good if you're editing large files on a daily basis maybe, but i'm not... 
set number                 " everyone loves row numbers 
set ruler                  " show information about current row/col 
set showcmd                " show useful information about the current state of keyboard input in normal mode
set showtabline=2          " always show the tab bar
filetype plugin indent on  " base indentation on filetype

let mapleader=","   " the leader key should be easy to type (',' is easier than '\')
colorscheme desert  " fancy colors ftw
syntax on           " enable syntax highlighting depending on file type

" Whitespacing and line/row breaks
set tabstop=2                                       " a tab is two spaces
set shiftwidth=2                                    " indentation should follow tabstop, or stuff will have different indentation
set expandtab                                       " expand tabs into spaces
set nowrap                                          " seriously, don't wrap by default
set linebreak                                       " break on word barriers
set listchars=tab:»·,trail:·,precedes:<,extends:>   " highlight these little bastard when 'set list' is invoked
set backspace=indent,eol,start                      " backspace through everything in insert mode

" Searching
set hlsearch    " highlight matches
set incsearch   " incremental searching
set ignorecase  " searches are case insensitive...
set smartcase   " ... unless they contain at least one capital letter

" Tab completion behavior when opening files
set wildmode=list:longest,list:full  " complete as much as possible, then full for each press on tab

" Turn off hithe last search
map <silent> <C-L> :set hlsearch! hlsearch?<CR>

" When moving around using j/k, jump _within_ wrapped lines too (since you probably don't want to skip an entire paragraph).
nnoremap j gj
nnoremap k gk

" Allow saving of files as sudo when you forget to start vim using sudo.
cmap w!! %!sudo tee > /dev/null %
