set nocompatible

set ruler
set number

colorscheme desert
syntax on

" Whitespacing and line/row breaks
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set wrap
set linebreak
set listchars=tab:»·,trail:·,precedes:<,extends:>

" Searching
set incsearch
set ignorecase
set hlsearch
set smartcase

" Tab completion
set wildmode=list:longest,list:full

" Always show the status bar
set laststatus=2

" Don't let Command-T show gazillions of lines
let g:CommandTMaxHeight=20

